### PR TITLE
Create Issues

### PR DESCRIPTION
**Pull request by pushpendra050**
Sir I have stated my problem How can I stores the function (converted from symbolic expression) in a list of a list. so that when needed I can evaluate it by substituting my values. 
Thanks

### CODE REVIEW

**Comment by jankoslavic** [comment]
Dear @pushpendra050 this does not look good/clear to me. please prepare a working and simple snippet that will show on one hand how you do it currently and it works, and on the other hand how are you planning to use numbafy and it does not work.

**Comment by pushpendra050** [comment]
Sir, Here I have prepare a simple snippet and please do have a look 👍 

## Using Lambdafy 
import sympy as sp
from numbafy import numbafy
from numba import jit
from sympy.matrices import Matrix
import time

time1= time.time()
a,b= sp.symbols('a b')
Ufunc= [Matrix([[a,b],[b,a]]),Matrix([[a**2,b**2],[b**2,a**2]])]  ## b**2** is b square
### Ufunc contains two symbolic expression in form of sympy Matrix -> [1st expression, 2nd Expression ]

Ulambdify =[sp.lambdify([[a,b]],Ufunc[i]) for i in range(2)]
### Ulambdify stores all the conversion from expression to function in a form of list

val= [[1,2],[3,4]] 
### val contains all the different values of a and b needed to be substitute in the function

Usubs= [[Ulambdify[i](val[j]) for j in list(range(2))]for i in range(2)]
### Usubs taking the 1st expression and substituting the first combination of a and b i.e [1,2] then [3,4] and stores in a form of list of list -> [[1st expression with val[0], 1st expression with val[1]], [2nd expression with val[0], 2nd Expression with val[1]]]
time2=time.time()
print('computation has taken ',time2-time1,'seconds\n',Usubs)

output - This is the output from the above function 

computation has taken  0.002023458480834961 seconds
 [ **[array([[1, 2],
            [2, 1]]), 
array([[3, 4],
         [4, 3]])]**### ,
 **[array([[1, 4],
            [4, 1]]), 
array([[ 9, 16],
       [16,  9]])]** ]

##Using Numbafy
### I was having a hard time in using numbafy in terms of list of list like this
a,b= sp.symbols('a b')
Ufunc= [Matrix([[a,b],[b,a]]),Matrix([[a**2,b**2],[b**2,a**2]])]
Ulambdify=[numbafy(Ufunc[i],[a,b]) for i in range(2)]
exec_list=[exec(Ulambdify[i]) for i in range(2)]
val= [[1,2],[3,4]]
numbafy_func(val[0][0],val[0][1]) 
### here it will give the substitution of the first combination available in val i.e [1,2] in the 2nd Expression and we can not get the first expression it is lost.

## so only way to do this we need to use for loop 
time1= time.time()
Usubs= []
for i in range(2):
    f=numbafy(Ufunc[i],[a,b])
    exec(f)
    for j in range(2):
        g=numbafy_func(val[j][0],val[j][1])
        Usubs.append(g)
time2=time.time()
print('computation has taken ',time2-time1,'seconds\n',Usubs)

output-

computation has taken  0.0997629165649414 seconds
 [**Matrix([
[1, 2],
[2, 1]]), Matrix([
[3, 4],
[4, 3]])**, **Matrix([
[1, 4],
[4, 1]]), Matrix([
[ 9, 16],
[16,  9]]**)]


## I was looking for a much more elegant method to do that. I am having a symbolic expression in the form of sympy Matrix and I would like to substitute different values available in another list so how to do that?

## Please if possible try to look at my code and if your developed numbafy can be used here then please just show me how to do that for this case. for my problem, I will implement it after some time. 

## Thanks a lot for your valuable time

**Comment by jankoslavic** [comment]
Dear @pushpendra050 I am not sure this is a good case for numbafy. The package numbafy excels with huge equations. I had equations that were MB long if you saved them as txt. 

Please see the showcase:
https://github.com/jankoslavic/numbafy/blob/master/Showcase.ipynb

Sorry, it looks like I cannot help!

**Comment by pushpendra050** [comment]
Thank you for giving me your valuable time. its Okay sir.
but I wanted it to work for a very simple case, I have sympy Matrix, then I am converting it into list then using the numbafy and after importing math, I am evaluating it . but again I am getting error 

Please do see the snippet :

import sympy as sp
from math import sin,cos
from numbafy import numbafy
from numba import jit

Q1,Q2= sp.symbols('Q1 Q2')
func= sp.Matrix([
   [-sp.cos(Q1),  sp.sin(Q1), 0, -6*sp.cos(Q1)],
   [-sp.sin(Q1), -sp.cos(Q1), 0, -6*sp.sin(Q1)],
   [       0,        0, 0,          0],
   [       0,        0, 0,          0]])
f1= numbafy(func.tolist(),[Q1,Q2],use_cse=False)
exec(f1)
numbafy_func(1,1)



Output is 
<string>:1: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function numbafy_func failed at nopython mode lowering due to: 

File "<string>", line 6:
<source missing, REPL/exec in use?>

[1] During: lowering "$0.40 = build_list(items=[Var($0.14, <string> (6)), Var($0.29, <string> (6)), Var($0.34, <string> (6)), Var($0.39, <string> (6))])" at <string> (6)
C:\Users\Pushpendra\Anaconda3\lib\site-packages\numba\compiler.py:742: NumbaWarning: Function "numbafy_func" was compiled in object mode without forceobj=True.

File "<string>", line 1:
<source missing, REPL/exec in use?>

  self.func_ir.loc))
C:\Users\Pushpendra\Anaconda3\lib\site-packages\numba\compiler.py:751: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "<string>", line 1:
<source missing, REPL/exec in use?>

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))

[[-0.5403023058681398, 0.8414709848078965, 0, -3.2418138352088386],
 [-0.8414709848078965, -0.5403023058681398, 0, -5.048825908847379],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]

Could you sir tell me how to get rid of that error

**Comment by jankoslavic** [comment]
Ok... I am now with you and understand your needs... I would do it like this:

```
import sympy as sp
from math import sin,cos
from numbafy import numbafy
from numba import jit
import numpy as np

Q1,Q2= sp.symbols('Q1 Q2')
func= sp.Matrix([
[-sp.cos(Q1), sp.sin(Q1), 0, -6*sp.cos(Q1)],
[-sp.sin(Q1), -sp.cos(Q1), 0, -6*sp.sin(Q1)],
[ 0, 0, 0, 0],
[ 0, 0, 0, 0]])

flat_list = [item for sublist in func.tolist() for item in sublist]

numbafy_list = []
for exp in flat_list:
    f1 = numbafy(exp,[Q1,Q2],use_cse=True)
    exec(f1)
    numbafy_list.append(numbafy_func)

np.array([_(1,1) for _ in numbafy_list]).reshape(4,-1)
```

does this help?

**Comment by pushpendra050** [comment]
Sir, I had shared
merge_from_ofoct (1)
 a notebook regarding the same. If you get time please do have a look. Thanks

**Comment by jankoslavic** [comment]
I have two comments:
1. the timing is not correct: currently, it is also counting the compilation time (at huge equations this can take seconds) which is done only once
2. the numbafy makes sense with huge equations which you probably have, `use_cse=True` can have a significant impact on performance.

I will close this issue.

**Comment by pushpendra050** [comment]
Thank you so much sir, I did understand a lot how it is working and will try to implement it accordingly. I am really sorry to bother you for all the issues which I was facing. Now I am in much better position to change it as per my needs.

Regards
Pushpendra

**Pull request closed without merging**
